{
  "kind": "discovery#restDescription",
  "etag": null,
  "discoveryVersion": "v1",
  "id": "chromemanagement:v1",
  "name": "chromemanagement",
  "canonicalName": "Chrome Management",
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "revision": "20220425",
  "title": "Chrome Management API",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "http://developers.google.com/chrome/management/",
  "protocol": "rest",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "servicePath": "",
  "batchPath": "batch",
  "version_module": true,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from Chrome OS devices or users managed within your organization"
        }
      }
    }
  },
  "resources": {
    "customers": {
      "resources": {
        "apps": {
          "resources": {
            "android": {
              "resources": {},
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.android.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            },
            "chrome": {
              "resources": {},
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            },
            "web": {
              "resources": {},
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "countChromeAppRequests": {
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "description": "Generate summary of app installation requests.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "reports": {
          "resources": {},
          "methods": {
            "countChromeVersions": {
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "httpMethod": "GET",
              "description": "Generate report of installed Chrome versions.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "countInstalledApps": {
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "httpMethod": "GET",
              "description": "Generate report of app installations.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "findInstalledAppDevices": {
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "description": "Generate report of devices that have a specified app installed.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "resources": {},
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "path": "v1/{+parent}/telemetry/devices",
                  "httpMethod": "GET",
                  "description": "List all telemetry devices.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {}
        }
      },
      "methods": {}
    }
  },
  "methods": {}
}