{
  "kind": "discovery#restDescription",
  "etag": null,
  "discoveryVersion": "v1",
  "id": "searchconsole:v1",
  "name": "searchconsole",
  "canonicalName": "Search Console",
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "revision": "20220425",
  "title": "Google Search Console API",
  "description": "The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/webmaster-tools/search-console-api/",
  "protocol": "rest",
  "baseUrl": "https://searchconsole.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://searchconsole.googleapis.com/",
  "servicePath": "",
  "batchPath": "batch",
  "version_module": true,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/webmasters": {
          "description": "View and manage Search Console data for your verified sites"
        },
        "https://www.googleapis.com/auth/webmasters.readonly": {
          "description": "View Search Console data for your verified sites"
        }
      }
    }
  },
  "resources": {
    "searchanalytics": {
      "resources": {},
      "methods": {
        "query": {
          "id": "webmasters.searchanalytics.query",
          "path": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "httpMethod": "POST",
          "description": "Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "sitemaps": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "webmasters.sitemaps.delete",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "DELETE",
          "description": "Deletes a sitemap from the Sitemaps report. Does not stop Google from crawling this sitemap or the URLs that were previously crawled in the deleted sitemap.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "webmasters.sitemaps.get",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "GET",
          "description": "Retrieves information about a specific sitemap.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "webmasters.sitemaps.list",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "httpMethod": "GET",
          "description": " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request).",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "submit": {
          "id": "webmasters.sitemaps.submit",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "PUT",
          "description": "Submits a sitemap for a site.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "sites": {
      "resources": {},
      "methods": {
        "add": {
          "id": "webmasters.sites.add",
          "path": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "PUT",
          "description": " Adds a site to the set of the user's sites in Search Console.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "delete": {
          "id": "webmasters.sites.delete",
          "path": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "DELETE",
          "description": " Removes a site from the set of the user's Search Console sites.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "webmasters.sites.get",
          "path": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "GET",
          "description": " Retrieves information about specific site.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "webmasters.sites.list",
          "path": "webmasters/v3/sites",
          "httpMethod": "GET",
          "description": " Lists the user's Search Console sites.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "urlInspection": {
      "resources": {
        "index": {
          "resources": {},
          "methods": {
            "inspect": {
              "id": "searchconsole.urlInspection.index.inspect",
              "path": "v1/urlInspection/index:inspect",
              "httpMethod": "POST",
              "description": "Index inspection.",
              "scopes": [
                "https://www.googleapis.com/auth/webmasters",
                "https://www.googleapis.com/auth/webmasters.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {}
    },
    "urlTestingTools": {
      "resources": {
        "mobileFriendlyTest": {
          "resources": {},
          "methods": {
            "run": {
              "id": "searchconsole.urlTestingTools.mobileFriendlyTest.run",
              "path": "v1/urlTestingTools/mobileFriendlyTest:run",
              "httpMethod": "POST",
              "description": "Runs Mobile-Friendly Test for a given URL.",
              "scopes": [],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {}
    }
  },
  "methods": {}
}