[workspace]

members = [
    "abusiveexperiencereport/v1/lib",
    "acceleratedmobilepageurl/v1/lib",
    "adexchangebuyer/v1.2/lib",
    "adexchangebuyer/v1.3/lib",
    "adexchangebuyer/v1.4/lib",
    "adexperiencereport/v1/lib",
    "admin/datatransfer_v1/lib",
    "admin/reports_v1/lib",
    "analyticsreporting/v4/lib",
    "androidenterprise/v1/lib",
    "androidpublisher/v1/lib",
    "androidpublisher/v1.1/lib",
    "appstate/v1/lib",
    "bigtableadmin/v1/lib",
    "blogger/v3/lib",
    "cloudasset/v1/lib",
    "cloudresourcemanager/v1/lib",
    "cloudresourcemanager/v1beta1/lib",
    "cloudshell/v1/lib",
    "commentanalyzer/v1alpha1/lib",
    "compute/beta/lib",
    "compute/v1/lib",
    "content/v2/lib",
    "content/v2.1/lib",
    "datastore/v1beta1/lib",
    "datastore/v1beta3/lib",
    "deploymentmanager/alpha/lib",
    "deploymentmanager/v2beta/lib",
    "deploymentmanager/v2/lib",
    "digitalassetlinks/v1/lib",
    "dns/v1/lib",
    "dns/v1beta2/lib",
    "dns/v2beta1/lib",
    "docs/v1/lib",
    "doubleclickbidmanager/v1/lib",
    "drive/v3/lib",
    "factchecktools/v1alpha1/lib",
    "firebasedynamiclinks/v1/lib",
    "gamesManagement/v1management/lib",
    "genomics/v1alpha2/lib",
    "genomics/v1/lib",
    "groupssettings/v1/lib",
    "iap/v1/lib",
    "iap/v1beta1/lib",
    "indexing/v3/lib",
    "kgsearch/v1/lib",
    "language/v1/lib",
    "language/v1beta1/lib",
    "language/v1beta2/lib",
    "licensing/v1/lib",
    "pagespeedonline/v1/lib",
    "pagespeedonline/v2/lib",
    "pagespeedonline/v4/lib",
    "pagespeedonline/v5/lib",
    "plus/v1/lib",
    "plusDomains/v1/lib",
    "pubsub/v1beta1a/lib",
    "remotebuildexecution/v2/lib",
    "replicapool/v1beta1/lib",
    "reseller/v1/lib",
    "runtimeconfig/v1/lib",
    "servicebroker/v1/lib",
    "servicecontrol/v1/lib",
    "siteVerification/v1/lib",
    "sqladmin/v1beta4/lib",
    "storage/v1beta1/lib",
    "storagetransfer/v1/lib",
    "streetviewpublish/v1/lib",
    "surveys/v2/lib",
    "texttospeech/v1/lib",
    "texttospeech/v1beta1/lib",
    "urlshortener/v1/lib",
    "videointelligence/v1p1beta1/lib",
    "videointelligence/v1p2beta1/lib",
    "videointelligence/v1p3beta1/lib",
    "videointelligence/v1beta2/lib",
    "webmasters/v3/lib",
    "youtubeAnalytics/v1/lib",
    "youtubeAnalytics/v2/lib",
]